Implements Tailwind
Marandino-Dev/rorro pull request #1
Opened 2024-08-13 14:58 UTC by K3iiX

Installs

- Tailwindcss 
- Postcss 
- Autoprefixer

2024-08-13 15:00 UTC, marandino requested changes

2024-08-13 15:00 UTC, marandino commented on package.json
> +    "tailwindcss": "^3.4.9",
```suggestion
    "autoprefixer": "^10.4.20",
    "eslint": "8",
    "eslint-config-next": "14.2.2",
    "postcss": "8.4.41",
    "tailwindcss": "3.4.9",
```

2024-08-13 15:00 UTC, marandino commented on tailwind.config.js
> +    extend: {},
This will need to have the color palette we will be using

2024-08-14 15:56 UTC, marandino approved these changes

2024-08-14 16:00 UTC, nenedac approved these changes
LGTM MGLBC

2024-08-14 16:01 UTC, merged